sudo: required
language: javascript
services:
  - docker
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
before_install:
  - docker version
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
install:
  - npm install
  - docker pull empiricalci/test_standalone
  - docker run -d -P --name rethink1 rethinkdb
  - docker run -d -p 1337 --net host --entrypoint=npm empiricalci/empirical run test-server
  - docker build -t empiricalci/emp:test .
script:
  - npm run lint
  - npm run test-cov
  - npm run test-cli
  - npm run test-launcher
