version: '2'
services:
  emp-test-circle:
    build: .
    image: empiricaladmin/emp
    entrypoint: npm
    command: run test
    env_file: auth.env
    environment:
      - EMPIRICAL_ENV=test
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empirical:5555
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - empirical
  emp-test:
    build: .
    image: empiricaladmin/emp
    entrypoint: npm
    command: run test
    environment:
      - EMPIRICAL_ENV=test
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empirical:5555
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - empirical
  empirical:
    image: alantrrs/empirical
    entrypoint: npm
    command: run test-server
    hostname: empirical
    expose:
      - 5555
    environment:
      - PORT=5555
      - NODE_ENV=test
      - TEST_DB=mongodb://mongo/empirical-test-db
    links:
      - mongo
  mongo:
    image: mongo
  queue:
    container_name: rabbit-emp
    image: rabbitmq:3
    hostname: empirical-queue
    ports:
      - "5672:5672"
  emp_dev:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/emp
    environment:
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_KEY=$EMPIRICAL_KEY
      - EMPIRICAL_SECRET=$EMPIRICAL_SECRET
    tty: true
    stdin_open: true
    links:
      - queue

  emp_staging:
    extends:
      service: emp
    environment:
      - EMPIRICAL_ENV=staging
      - EMPIRICAL_AMQP_URL=$EMPIRICAL_AMQP_URL_STAGING
  emp:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/emp
    tty: true
    stdin_open: true
