version: '2'
services:
  emp-test-circle:
    build: .
    image: empiricaladmin/emp
    entrypoint: npm
    command: run test
    env_file: auth.env
    environment:
      - DOCKER_USER=empiricaladmin
      - EMPIRICAL_ENV=test
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empirical:5555
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - empirical
  emp-test:
    build: .
    image: empiricaladmin/emp
    entrypoint: npm
    command: run test
    environment:
      - EMPIRICAL_ENV=test
      - DOCKER_USER=empiricaladmin
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empirical:5555
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - empirical
  empirical:
    image: alantrrs/empirical
    entrypoint: npm
    command: run test-server
    container_name: empirical
    hostname: empirical
    expose:
      - 5555
    environment:
      - PORT=5555
      - NODE_ENV=test
      - TEST_DB=mongodb://mongo/empirical-test-db
    links:
      - mongo
  mongo:
    image: mongo
  queue:
    container_name: rabbit-emp
    image: rabbitmq:3
    hostname: empirical-queue
    ports:
      - "5672:5672"
  emp-dev:
    build: .
    entrypoint: bash
    image: empiricaladmin/emp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./package.json:/emp/package.json
      - ./lib:/emp/lib
      - ./test:/emp/test
      - ./config:/emp/config
      - ./index.js:/emp/index.js
    environment:
      - DOCKER_USER=empiricaladmin
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empirical:5555
    stdin_open: true
    links:
      - empirical
      - queue
