version: '2'
services:
  emp-test:
    build: .
    image: empiricalci/emp
    entrypoint: npm
    command: run test-cov
    environment:
      - CIRCLECI=$CIRCLECI
      - EMPIRICAL_ENV=test
      - DOCKER_USER=empiricaladmin
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empiricaldev.localtunnel.me
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: 'host'
    depends_on:
      - empirical
  empirical:
    image: empiricalci/empirical
    entrypoint: npm
    command: run test-server
    container_name: empirical
    hostname: empirical
    ports:
      - "5555:5555"
    environment:
      - LOCALTUNNEL=true
      - PORT=5555
      - TEST_DB=mongodb://mongo/empirical-test-db
    links:
      - mongo
  mongo:
    image: mongo
  queue:
    container_name: rabbit-emp
    image: rabbitmq:3
    hostname: empirical-queue
    ports:
      - "5672:5672"
  emp:
    build: .
    network_mode: 'host'
    entrypoint: npm start
    image: empiricalci/emp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./package.json:/emp/package.json
      - ./lib:/emp/lib
      - ./test:/emp/test
      - ./config:/emp/config
      - ./index.js:/emp/index.js
    environment:
      - DOCKER_USER=empiricaladmin
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=$EMPIRICAL_API_KEY
      - EMPIRICAL_API_SECRET=$EMPIRICAL_API_SECRET
      - EMPIRICAL_AMQP_URL=amqp://localhost:5672
    stdin_open: true
    depends_on:
      - queue
