version: '2'
services:
  emp-test:
    build: .
    image: empiricalci/emp
    entrypoint: npm
    command: run test-cov
    environment:
      - CIRCLECI=$CIRCLECI
      - DEBUG=$DEBUG
      - EMPIRICAL_ENV=test
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_DIR=/tmp/
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://$LOCALTUNNEL.tunnel.empiricalci.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/empirical/data
      - /tmp/workspaces:/empirical/workspaces
    network_mode: 'host'
    depends_on:
      - empirical
      - tunnel
  tunnel:
    image: empiricalci/empirical
    entrypoint: lt -p 5555 -s $LOCALTUNNEL -h http://tunnel.empiricalci.com
    network_mode: 'host'
  empirical:
    image: empiricalci/empirical
    entrypoint: npm
    command: run test-server
    container_name: empirical
    hostname: empirical
    ports:
      - "5555:5555"
    environment:
      - LOCALTUNNEL=$LOCALTUNNEL
      - PORT=5555
      - TEST_DB=mongodb://mongo/empirical-test-db
    links:
      - mongo
  mongo:
    image: mongo
  queue:
    container_name: rabbit-emp
    image: rabbitmq:3
    hostname: empirical-queue
    ports:
      - "5672:5672"
  emp:
    build: .
    image: empiricalci/emp
    network_mode: 'host'
    entrypoint: npm
    command: start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./package.json:/emp/package.json
      - ./lib:/emp/lib
      - ./test:/emp/test
      - ./config:/emp/config
      - ./index.js:/emp/index.js
      - $EMPIRICAL_DIR/data:/empirical/data
      - $EMPIRICAL_DIR/workspaces:/empirical/workspaces
    environment:
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56fa1e9c444d666624705d15
      - EMPIRICAL_API_SECRET=9b01c60c-56de-4ff2-8604-802c99f11d72
      - EMPIRICAL_AMQP_URL=amqp://localhost:5672
      - EMPIRICAL_API_URI=$EMPIRICAL_API_URI
      - EMPIRICAL_DIR=$EMPIRICAL_DIR
    stdin_open: true
    depends_on:
      - queue
