version: '2'
services:
  emp-test:
    build: .
    image: empiricalci/emp:test
    entrypoint: npm
    command: run test-cov
    environment:
      - CIRCLECI=$CIRCLECI
      - DEBUG=$DEBUG
      - EMPIRICAL_ENV=test
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_DIR=/tmp/
      - EMPIRICAL_API_URI=http://localhost:5555
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/data:/empirical/data
      - /tmp/workspaces:/empirical/workspaces
    network_mode: 'host'
    depends_on:
      - empirical
  empirical:
    image: empiricalci/empirical
    entrypoint: npm
    command: run test-server
    container_name: empirical
    hostname: empirical
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
      - TEST_DB=mongodb://mongo/empirical-test-db
    links:
      - mongo
  mongo:
    image: mongo
  queue:
    container_name: rabbit-emp
    image: rabbitmq:3
    hostname: empirical-queue
    ports:
      - "5672:5672"
  emp:
    build: .
    image: empiricalci/emp
    network_mode: 'host'
    entrypoint: npm
    command: start
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./package.json:/emp/package.json
      - ./lib:/emp/lib
      - ./test:/emp/test
      - ./config:/emp/config
      - ./index.js:/emp/index.js
      - ./listen.js:/emp/listen.js
      - $EMPIRICAL_DIR/data:/empirical/data
      - $EMPIRICAL_DIR/workspaces:/empirical/workspaces
    environment:
      - DEBUG=$DEBUG
      - DOCKER_USER=$DOCKER_USER
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_AMQP_URL=amqp://localhost:5672
      - EMPIRICAL_API_URI=$EMPIRICAL_API_URI
      - EMPIRICAL_DIR=$EMPIRICAL_DIR
    stdin_open: true
    depends_on:
      - queue
