version: '2'
services:
  emp-test:
    build: .
    image: empiricaladmin/emp
    entrypoint: npm
    command: run test
    environment:
      - EMPIRICAL_ENV=test
      - DOCKER_AUTH=$DOCKER_AUTH
      - EMPIRICAL_API_KEY=56f21e9c444d700624705d16
      - EMPIRICAL_API_SECRET=e6bbfb2b-f608-48a8-8a60-c78df6c2bb97
      - EMPIRICAL_API_URI=http://empirical:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - empirical-test:empirical

  empirical-test:
    image: alantrrs/empirical
    entrypoint: npm
    command: run test-server
    expose:
      - 8080
    environment:
      - PORT=8080
      - NODE_ENV=test
      - TEST_DB=mongodb://mongo/empirical-test-db
    links:
      - mongo
  mongo:
    image: mongo
